env:
  secure: Iw6We5llE84rNMruXfyJGD2sYW055ltM3neEkQQeuW+5qSxcJJzm3dsofamVG8WCijNh9E5wK8hYdia5xvKWxFmcHCOnD4hqieLGBb3hE0/knW14u72Nek8lNQZ+20QhJn2vNQNerQK/iaRhzxgyL1y+vseiXbMWcZpTk57DZygo3+ycrKbXJbz0sjP8IszKfDv9SRueGn6XKQbaZBNtaXYMNO/VHbzobpnzOLSkf7Mk/rRqpaDRDao6ct8jaluTtWdzOu7Z41mTkAOeWLfi5ieg2DgeU1PZgaSAeK/hH9ygSrLI4eRRb7lqMiKWPVV04uD3GpqoXOulbKiJ3bOQ7dVgh/jOLplz9nmRFYyg3D271yiPRCN9ButDh3jFYdu6aY/uq/QfRU0h95hZf7vzuAtnbtTh6XMEt3ysURGURJXcyNxrq2gPKdRqrY0TUan4tz7ZrvyKAgAjqY7pZNtAG7pbEnDC2sRJeEN6tVD3Bcbf2figUv4achMbFNFZjTbZyH0fAywiGeDipKc1YEINMEdAIA0DZGWAuGB2uR81rcM6DaC2Jg/uaXmsSqOP3T/BPPlS5opGwSDz3JiwoZfwhErHG/OVQ4CJrA4A/M/K1KD4i/rKDICv4SaHZGwXJuB92fNOznE4EWpFJDD1ZR32VqgVGohRG2T2hHC7rQW1brY=
language: ruby
dist: focal
rvm:
- 2.6.6
cache:
  directories:
  - node_modules
  - vendor/bundle
before_install:
- gem install bundler:2.1.4
- nvm install 12.13.1
- npm install -g yarn@1.22.4
before_script:
- bundle install
- yarn install
script:
- bundle exec rake db:drop
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec
- bundle exec cucumber
